homeassistant: true
mqtt:
  server: mqtt://core-mosquitto:1883
  user: addons
  password: '!secret mqtt_password'
serial:
  port: /dev/ttyUSB1
frontend:
  port: 8080
advanced:
  homeassistant_legacy_entity_attributes: false
  legacy_api: false
  legacy_availability_payload: false
  log_level: info
  log_syslog:
    app_name: Zigbee2MQTT
    eol: /n
    host: localhost
    localhost: localhost
    path: /dev/log
    pid: process.pid
    port: 514
    protocol: udp4
    type: '5424'
  transmit_power: 20
  last_seen: ISO_8601_local
device_options:
  legacy: false
permit_join: true
devices:
  '0x00124b00246ca33d':
    friendly_name: Hallway Plug
  '0x00124b00246c9dbe':
    friendly_name: Kitchen Plug
  '0x00124b00246caf47':
    friendly_name: Utility Plug
  '0x00124b00246ca011':
    friendly_name: Landing Plug
  '0x00124b00292998ac':
    friendly_name: Front Door
  '0x00124b0022d5a09d':
    friendly_name: En Suite Climate
  '0x00124b0022d5dc06':
    friendly_name: Master Bedroom Climate
  '0x00124b00246cefa3':
    friendly_name: Living Room TV
  '0x00124b0029197bbf':
    friendly_name: Closet Climate
  '0x7cb94c7788dc0000':
    friendly_name: Office Plug
  '0x00124b0029298c5f':
    friendly_name: Office Door
  '0x0017880108f6699a':
    friendly_name: Sonos Dimmer
    legacy: true
  '0x00124b00246ce913':
    friendly_name: Master Bedroom Plug
  '0x00124b0029dedd43':
    friendly_name: Zigbee USB Router
  '0x00124b00292931e4':
    friendly_name: Stairs Motion
  '0x00124b00292927c7':
    friendly_name: En Suite Door
  '0x00124b0029296de4':
    friendly_name: Upstairs Landing Motion
  '0x00124b00292831c5':
    friendly_name: Master Bedroom Motion
  '0x8cf681fffeba49ed':
    friendly_name: Living Room Remote
availability:
  active:
    timeout: 10
  passive:
    timeout: 1500
