- id: '1672786399713'
  alias: Home - Battery Notifications
  description: ''
  use_blueprint:
    path: sbyx/low-battery-level-detection-notification-for-all-battery-sensors.yaml
    input:
      threshold: 15
      day: 6
      exclude:
        entity_id:
        - sensor.adam_s_ipad_battery_level
        - sensor.adams_iphone_battery_level
      actions:
      - device_id: 5459415477ca3de54c37573b258cf625
        domain: mobile_app
        type: notify
        message: Batteries need changing!
        title: 'The following sensors need batteries changing: {{sensors}}'
- id: '1673389901443'
  alias: Go to bed
  description: ''
  trigger: []
  condition: []
  action:
  - parallel:
    - type: turn_off
      device_id: 0c8e824e74f016ac8e00be47a0268dee
      entity_id: light.hallway_toilet
      domain: light
    - type: turn_off
      device_id: fa9fca7bea24e9cd3da84140d3ea352a
      entity_id: light.living_room
      domain: light
  - type: turn_on
    device_id: 359198f42ca411dbc14ee570528b46bf
    entity_id: light.front_door
    domain: light
    brightness_pct: 35
  - device_id: a5bdac38fdd1ff4ee52a5007404f404c
    domain: climate
    entity_id: climate.kitchen
    type: set_preset_mode
    preset_mode: eco
  - service: media_player.turn_off
    data: {}
    target:
      entity_id: media_player.65oled806_12
  - type: turn_on
    device_id: 76497eb01548d2962b637dce29e2d5c1
    entity_id: light.lamp
    domain: light
    brightness_pct: 100
  - delay:
      hours: 0
      minutes: 0
      seconds: 45
      milliseconds: 0
  - type: turn_off
    device_id: 359198f42ca411dbc14ee570528b46bf
    entity_id: light.front_door
    domain: light
  mode: single
- id: '1674200143844'
  alias: Music Tag - Evanescence Fallen is scanned
  description: ''
  trigger:
  - platform: tag
    tag_id: f77bb2b0-76f7-492c-b307-fe8ef63dd77f
  condition: []
  action:
  - service: media_player.volume_set
    data:
      volume_level: 0.25
    target:
      entity_id:
      - media_player.main_bedroom
  - service: media_player.play_media
    target:
      entity_id: media_player.main_bedroom
    data:
      media_content_id: plex://4f86a96668a6ebc2ffe96dd49cb8c39e0d77db1e/11328
      media_content_type: album
    metadata:
      title: Fallen (2003)
      thumbnail: https://178-78-103-57.15eff6ade6294647acafa8ad308ab407.plex.direct:32400/library/metadata/11328/thumb/1673910877?X-Plex-Token=9zKNT1PjZVsPPZa4sqQF
      media_class: album
      children_media_class:
      navigateIds:
      - {}
      - media_content_type: plex
        media_content_id: ''
      - media_content_type: library
        media_content_id: plex://4f86a96668a6ebc2ffe96dd49cb8c39e0d77db1e/4
      - media_content_type: artist
        media_content_id: plex://4f86a96668a6ebc2ffe96dd49cb8c39e0d77db1e/11327
  mode: single
- id: '1674821169405'
  alias: Office - Lighting
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.office_sensor_motion
    - binary_sensor.office_presence
    for:
      hours: 0
      minutes: 0
      seconds: 0
  condition: []
  action:
  - if:
    - condition: time
      after: '17:30:00'
      before: 08:00:00
    then:
    - service: scene.turn_on
      target:
        entity_id: scene.play_time
      metadata: {}
    else:
    - service: scene.turn_on
      target:
        entity_id: scene.work_time
      metadata: {}
  trace:
    stored_traces: 50
  mode: single
- id: '1674842920963'
  alias: Theatre Mode
  description: ''
  use_blueprint:
    path: panhans/theatre_mode.yaml
    input:
      media_player: media_player.sky_q
      scene_playing: scene.living_room_chill
      scene_paused: scene.living_room_daytime_chill
      transition: 3
- id: '1682234657497'
  alias: Living Room - Daytime
  description: ''
  use_blueprint:
    path: freakshock88/motion_illuminance_activated_entity.yaml
    input:
      motion_sensor: binary_sensor.living_room_sensor_motion
      target_entity: scene.living_room_daytime_chill
      illuminance_sensor: sensor.living_room_sensor_illuminance
      sunstate_condition: Above horizon
      no_motion_wait: input_number.living_room_empty_wait_time
      illuminance_cutoff: input_number.low_light_level
- id: '1682234975513'
  alias: Living Room - Evening
  description: ''
  use_blueprint:
    path: freakshock88/motion_illuminance_activated_entity.yaml
    input:
      motion_sensor: binary_sensor.living_room_sensor_motion
      target_entity: script.living_chill_script
      illuminance_sensor: sensor.living_room_sensor_illuminance
      sunstate_condition: Below horizon
      no_motion_wait: input_number.living_room_empty_wait_time
      illuminance_cutoff: input_number.low_light_level
- id: '1682283901871'
  alias: Hallway - Off
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.stairs_motion_occupancy
    to: 'off'
    for:
      hours: 0
      minutes: 5
      seconds: 0
  condition:
  - condition: template
    value_template: '{{ (as_timestamp(now())-as_timestamp(states.automation.living_room_nighttime.last_updated))
      > 150 }}'
  action:
  - type: turn_off
    device_id: cde7fca74567f8b9527f6590d1d5849a
    entity_id: light.hallway
    domain: light
  trace:
    stored_traces: 50
  mode: single
- id: '1682722209466'
  alias: Home - Off
  description: ''
  trigger:
  - platform: state
    entity_id:
    - person.adam_lonsdale
    from: home
    for:
      hours: 0
      minutes: 0
      seconds: 0
    to: not_home
  condition: []
  action:
  - service: scene.turn_on
    target:
      entity_id: scene.all_off
    metadata: {}
  trace:
    stored_traces: 50
  mode: single
- id: '1682723299240'
  alias: Home - Return
  description: ''
  trigger:
  - platform: state
    entity_id:
    - person.adam_lonsdale
    from: not_home
    to: home
  - type: motion
    platform: device
    device_id: ee20d67f1210e69f4bf00baeb5dd4254
    entity_id: binary_sensor.office_sensor_motion
    domain: binary_sensor
  condition: []
  action:
  - wait_for_trigger:
    - platform: state
      entity_id:
      - binary_sensor.front_door_contact
      from: 'off'
      to: 'on'
    continue_on_timeout: false
    timeout:
      hours: 0
      minutes: 10
      seconds: 0
      milliseconds: 0
  - if:
    - condition: numeric_state
      entity_id: sensor.living_room_sensor_illuminance
      attribute: light_level
      below: input_number.low_light_level
    then:
    - service: scene.turn_on
      target:
        entity_id: scene.welcome_home
      metadata: {}
  trace:
    stored_traces: 50
  mode: single
- id: '1682756163488'
  alias: Office - Off
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.office_sensor_motion
    for:
      hours: 0
      minutes: 2
      seconds: 30
    to: 'off'
  condition: []
  action:
  - service: scene.turn_on
    target:
      entity_id: scene.office_off
    metadata: {}
  trace:
    stored_traces: 50
  mode: single
- id: '1682808309962'
  alias: Living Room - Off
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.living_room_sensor_motion
    to: 'off'
    for:
      hours: 0
      minutes: 5
      seconds: 0
  condition: []
  action:
  - type: turn_off
    device_id: fa9fca7bea24e9cd3da84140d3ea352a
    entity_id: light.living_room
    domain: light
  mode: single
  trace:
    stored_traces: 50
- id: '1683100910566'
  alias: Controller - Philips 324131092621 Hue Dimmer switch
  description: ''
  use_blueprint:
    path: EPMatt/philips_324131092621.yaml
    input:
      integration: Zigbee2MQTT
      controller_entity: sensor.sonos_dimmer_action
      helper_last_controller_event: input_text.sonos_last_action
      action_button_up_short:
      - service: media_player.volume_up
        data: {}
        target:
          entity_id:
          - media_player.living_room
      action_button_off_short:
      - service: media_player.volume_mute
        data:
          is_volume_muted: true
        target:
          entity_id: media_player.living_room
      action_button_on_short:
      - service: media_player.volume_mute
        data:
          is_volume_muted: false
        target:
          entity_id: media_player.living_room
      action_button_down_short:
      - service: media_player.volume_down
        data: {}
        target:
          entity_id: media_player.living_room
      button_up_long_loop: true
      button_down_long_loop: true
      action_button_down_long:
      - service: media_player.volume_down
        data: {}
        target:
          entity_id: media_player.living_room
      action_button_up_long:
      - service: media_player.volume_up
        data: {}
        target:
          entity_id: media_player.living_room
      helper_debounce_delay: 50
- id: '1685360053965'
  alias: New Automation
  description: ''
  use_blueprint:
    path: N1c093/media-player-volume-limit.yaml
    input:
      media_player:
      - media_player.living_room
      volume_limit: 0.4
- id: '1685360742800'
  alias: Notification - Frigate - iPhone
  description: ''
  use_blueprint:
    path: SgtBatten/Stable.yaml
    input:
      camera: camera.outside
      notify_device: 5459415477ca3de54c37573b258cf625
      base_url: https://home.lonsdale.house
      title: Frigate Detection
      message: '{{ label }} detected - {{ camera_name }}'
      critical: 'false'
      alert_once: true
      attachment: snapshot
      update_thumbnail: true
      color: teal
      icon: mdi:{{'account-outline' if label == 'Person' else 'dog' if label == 'Dog'
        else 'cat' if label == 'Cat' else 'car' if label == 'Car' else 'home-assistant'}}
      ios_live_view: true
      zone_filter: false
      labels:
      - person
      - dog
- id: '1685361017425'
  alias: Notification - Frigate - TV
  description: ''
  use_blueprint:
    path: SgtBatten/Stable.yaml
    input:
      camera: camera.outside
      base_url: https://home.lonsdale.house
      title: Camera Alert!
      message: '{{ label }} detected - {{ camera_name }}'
      critical: 'true'
      alert_once: true
      attachment: snapshot
      update_thumbnail: true
      color: teal
      icon: mdi:{{'account-outline' if label == 'Person' else 'dog' if label == 'Dog'
        else 'cat' if label == 'Cat' else 'car' if label == 'Car' else 'home-assistant'}}
      ios_live_view: true
      zone_filter: false
      labels:
      - person
      - car
      - dog
      notify_group: media_player.android_tv_192_168_160_163
      tv: true
      tv_position: top-right
      tv_duration: 5
      tv_transparency: 25%
- id: '1685470047933'
  alias: Stairs - Descending - Night
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.upstairs_landing_motion_occupancy
    from: 'off'
    to: 'on'
  condition:
  - condition: numeric_state
    entity_id: sensor.living_room_sensor_illuminance
    attribute: light_level
    below: input_number.low_light_level
  action:
  - service: scene.turn_on
    target:
      entity_id: scene.hallway_path
    metadata: {}
  - wait_for_trigger:
    - platform: state
      entity_id:
      - binary_sensor.stairs_motion_occupancy
      from: 'off'
      to: 'on'
    continue_on_timeout: true
    timeout:
      hours: 0
      minutes: 2
      seconds: 0
      milliseconds: 0
  - service: scene.turn_on
    target:
      entity_id: scene.going_downstairs
    metadata: {}
  - if:
    - condition: state
      entity_id: binary_sensor.stairs_motion_occupancy
      state: 'on'
    then:
    - service: scene.turn_on
      target:
        entity_id: scene.going_downstairs
      metadata: {}
    else:
    - service: scene.turn_on
      target:
        entity_id: scene.living_room_off
      metadata: {}
  mode: single
- id: '1685470759226'
  alias: Stairs - Ascending - Night
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.stairs_motion_occupancy
    from: 'off'
    to: 'on'
  condition:
  - condition: numeric_state
    entity_id: sensor.office_sensor_illuminance
    attribute: light_level
    below: input_number.low_light_level
  action:
  - service: scene.turn_on
    target:
      entity_id: scene.hallway_path
    metadata: {}
  - wait_for_trigger:
    - platform: state
      entity_id:
      - binary_sensor.upstairs_landing_motion_occupancy
      from: 'off'
      to: 'on'
    timeout:
      hours: 0
      minutes: 4
      seconds: 0
      milliseconds: 0
  - if:
    - condition: state
      entity_id: binary_sensor.upstairs_landing_motion_occupancy
      state: 'on'
    then:
    - type: turn_on
      device_id: 76497eb01548d2962b637dce29e2d5c1
      entity_id: light.lamp
      domain: light
    - service: scene.turn_on
      target:
        entity_id: scene.going_upstairs
      metadata: {}
  - type: turn_off
    device_id: cde7fca74567f8b9527f6590d1d5849a
    entity_id: light.hallway
    domain: light
  mode: single
- id: '1685521177369'
  alias: Stairs - Ascending - Day
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.stairs_motion_occupancy
    from: 'off'
    to: 'on'
  condition:
  - condition: numeric_state
    entity_id: sensor.office_sensor_illuminance
    attribute: light_level
    above: input_number.low_light_level
  action:
  - wait_for_trigger:
    - platform: state
      entity_id:
      - binary_sensor.upstairs_landing_motion_occupancy
      from: 'off'
      to: 'on'
    timeout:
      hours: 0
      minutes: 4
      seconds: 0
      milliseconds: 0
    continue_on_timeout: false
  - type: turn_off
    device_id: cde7fca74567f8b9527f6590d1d5849a
    entity_id: light.hallway
    domain: light
  - type: turn_off
    device_id: fa9fca7bea24e9cd3da84140d3ea352a
    entity_id: light.living_room
    domain: light
  mode: single
- id: '1685521349740'
  alias: Stairs - Descending - Day
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.upstairs_landing_motion_occupancy
    from: 'off'
    to: 'on'
  condition:
  - condition: numeric_state
    entity_id: sensor.living_room_sensor_illuminance
    attribute: light_level
    above: input_number.low_light_level
  action:
  - wait_for_trigger:
    - platform: state
      entity_id:
      - binary_sensor.stairs_motion_occupancy
      from: 'off'
      to: 'on'
    continue_on_timeout: false
    timeout:
      hours: 0
      minutes: 2
      seconds: 0
      milliseconds: 0
  - type: turn_off
    device_id: 6c612d272705ea4fdcd149b1462bb079
    entity_id: light.office
    domain: light
  - type: turn_off
    device_id: 0d99e5aac74c2c30b513aa714dbbaa7b
    entity_id: light.master_bedroom_2
    domain: light
  mode: single
