
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes
  extra_module_url:
   - /config/www/community/lovelace-card-mod/card-mod.js

# Text to speech
tts:
  - platform: google_translate

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.22.0.0/16
    - 172.27.0.0/16

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
sensor: !include sensor.yaml

input_select: 
  house_presence:
    name: House Presence
    initial: Unknown #Default until actual state is known after restart
    options:
      - Unknown
      - Empty
      - Someone
      - Guests
      - Extended Away
      - Adam
  bedroom_presence:
    name: Bedroom Presence
    initial: Unknown #Default until actual state is known after restart
    options:
      - Unknown
      - Empty
      - Someone
      - Guests
      - Adam
      - Extended Away
      - Going to Sleep
      - Sleeping
      - Waking Up
      - Woken Up
  living_room_presence:
    name: Living Room Presence
    initial: Unknown #Default until actual state is known after restart
    options:
      - Unknown
      - Empty
      - Someone
      - Guests
      - Extended Away
      - Adam
  adam_location:
    name: Adam Location
    initial: Unknown #Default until actual state is known after restart
    options:
      - Unknown
      - Just Arrived
      - Home
      - Just Left
      - Away
      - Extended Away
      - Living Room
      - Bedroom

group: 
  person_locations:
    name: Person Locations
    entities:
      - input_select.adam_location
 
  person_home_away:
    name: Person Locations
    entities:
      - person.adam_lonsdale

template:
  - sensor:
    - name: "Calculated Light Brightness"
      unit_of_measurement: "Float"
      state: |
        {%- set lux = states('sensor.estimated_illuminance') | int(default=0) -%}
        {%- set perc = ((lux / (400 / 100))/200) | float -%}
        {{ perc }}
  - trigger:
    - platform: state
      entity_id:
        - climate.kitchen
    - platform: time_pattern
      minutes: "/5"
    binary_sensor:
    - name: "Kitchen Eco Mode"
      state: "{{ state_attr('climate.kitchen', 'preset_mode') == 'eco' }}"
    - name: "Kitchen Heating"
      state: "{{ state_attr('climate.kitchen', 'hvac_action') == 'heating' }}"

  - trigger:
    - platform: state
      entity_id:
        - remote.65oled806_12_remote
    - platform: time_pattern
      minutes: "/5"
    binary_sensor:
    - name: "Living TV On"
      state: "{{ states('remote.65oled806_12_remote') == 'on' }}"
      
  - trigger:
    - platform: state
      entity_id:
        - binary_sensor.office_sensor_motion
    binary_sensor:
    - name: "Office Presence"
      state: "{{ states('binary_sensor.office_sensor_motion') == 'on' }}"

homeassistant:
    customize: !include customize.yaml

influxdb:
    api_version: 2
    host: influxdb
    port: 8086
    ssl: false
    token: !secret influx_token
    organization: 4b506cab92110ea5
    bucket: Home
    max_retries: 5
    tags:
        instance: prod
        source: hass

o365: !include o365.yaml

homekit:
  - name: Home Assistant
    port: 21063
    filter:
      include_domains:
        - alarm_control_panel
        - light
        - climate
        - person
      include_entity_globs:
        - binary_sensor.*_occupancy
      include_entities:
        - binary_sensor.living_room_sensor_motion

        - sensor.living_room_sensor_temperature

        - sensor.closet_climate_temperature
        - sensor.closet_climate_humidity

        - sensor.en_suite_climate_temperature
        - sensor.en_suite_climate_humidity

        - sensor.hue_outdoor_motion_sensor_1_temperature

        - sensor.kitchen_temperature
        - sensor.kitchen_humidity

        - sensor.master_bedroom_climate_temperature
        - sensor.master_bedroom_climate_humidity

        - sensor.office_climate_temperature

      exclude_entity_globs:
        - "*espresen?e*"
      exclude_entities:
        - light.office_lightstrip
        - light.kitchen_lamp

    entity_config:
      alarm_control_panel.alarmo:
        code: !secret alarm_code

      binary_sensor.living_room_sensor_motion:
        linked_battery_sensor: sensor.living_room_sensor_battery
        low_battery_threshold: 31

      media_player.sky_q:
        name: Sky Q
        feature_list:
          - feature: on_off
          - feature: play_pause
          - feature: play_stop
          - feature: toggle_mute
  - name: Driveway Camera
    port: 21064
    mode: accessory
    filter:
      include_entities:
       - camera.outside
  - name: Garden Camera
    port: 21065
    mode: accessory
    filter:
      include_entities:
       - camera.office
  - name: Downstairs Garden Camera
    port: 21066
    mode: accessory
    filter:
      include_entities:
       - camera.kitchen

config_editor:

waste_collection_schedule:
  sources:
    - name: eastriding_gov_uk
      args:
        postcode: !secret property_postcode
        uprn: !secret property_uprn

mqtt:
  siren:
    - unique_id: alarm_siren
      name: "Intrusion Siren"
      command_topic: "zigbee2mqtt/Alarm Siren/set"
      command_template: "{\"warning\": {\"duration\": 10, \"mode\": \"{{ tone }}\" }}"
      command_off_template: "{\"warning\": {\"mode\": \"stop\" }}"
      available_tones:
        - emergency
      availability:
        - topic: "zigbee2mqtt/Alarm Siren/availability"
          payload_available: "{\"state\":\"online\"}"
      optimistic: false
      qos: 0
      retain: true

logger:
  default: warning
  logs:
    homeassistant.core: warning
    homeassistant.components.waste_collection_schedule: info
