  - platform: illuminance
    name: Estimated Illuminance
    entity_id: weather.openweathermap
  - platform: filter
    name: "Filtered Light Brightness"
    entity_id: sensor.calculated_light_brightness
    filters:
     - filter: range
       lower_bound: 0.2
       upper_bound: 1
  - platform: waste_collection_schedule
    source_index: 0
    name: eastriding_gov_uk
    add_days_to: true