version: '3'
services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:rc"
    volumes:
      - ./config:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    expose: 
      - "8123"
    networks:
      service_vnet:
      iot_macvlan:
        ipv4_address: 192.168.160.102
    
  emhass:
    container_name: emhass
    image: davidusb/emhass-docker-standalone:latest
    user: "${UID}:${GID}"
    restart: always
    ports:
      - 5000:5000
    environment:
      - LOCAL_COSTFUN=profit
    volumes:
      - ./emhass/config_emhass.yaml:/app/config_emhass.yaml
      - ./emhass/secrets_emhass.yaml:/app/secrets_emhass.yaml

  mdns-repeater:
    image: monstrenyatko/mdns-repeater
    container_name: mdns-repeater
    restart: unless-stopped
    command: mdns-repeater-app -f br0 br-c6f7fe3f6058
    network_mode: "host"

  esphome:
    container_name: esphome
    image: ghcr.io/esphome/esphome
    user: "${UID}:${GID}"
    volumes:
      - ./esphome/config:/config
      - ./esphome/cache:/cache
      - /etc/localtime:/etc/localtime:ro
    expose:
      - 6052
    restart: always
    privileged: true
    environment:
      PLATFORMIO_CORE_DIR: .plattformio
      PLATFORMIO_GLOBALLIB_DIR: .plattformioLibs
      ESPHOME_DASHBOARD_USE_PING: true
    networks:
      service_vnet:

  mqtt:
    image: eclipse-mosquitto:latest
    container_name: "mqtt"
    user: "${UID}:${GID}"
    restart: always
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - ./mqtt/data:/mosquitto/data
      - ./mqtt/config:/mosquitto/config
      - ./mqtt/log:/mosquitto/log
    environment:
      - TZ=Europe/London
    networks:
      service_vnet:
        aliases:
          - core-mosquitto
        
  zigbee2mqtt:
    container_name: zigbee2mqtt
    restart: always
    privileged: true
    image: koenkk/zigbee2mqtt:latest
    volumes:
      - ./zigbee2mqtt:/app/data
      - /run/udev:/run/udev:ro
    depends_on:
      mqtt:
        condition: service_started
    expose:
      - "8080"
    environment:
      - TZ=Europe/London
    networks:
      service_vnet:
    
  adguardhome:
    image: adguard/adguardhome
    container_name: adguardhome
    user: "${UID}:${GID}"
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 784:784/udp
      - 853:853/tcp
      - 80:80/tcp
      - 443:443/tcp
      - 3000:3000/tcp
    volumes:
      - ./adguard/workdir:/opt/adguardhome/work
      - ./adguard/confdir:/opt/adguardhome/conf
    networks:
      iot_macvlan:
        ipv4_address: 192.168.160.100
    restart: unless-stopped
    
  influxdb:
    image: influxdb:2.7
    container_name: influxdb
    user: "${UID}:${GID}"
    restart: always
    environment:
      - DOCKER_INFLUXDB_INIT_ORG=Lonsdale
      - DOCKER_INFLUXDB_INIT_BUCKET=Home
      - DOCKER_INFLUXDB_INIT_RETENTION=12w
    expose:
      - "8086"
    volumes:
      - ./influxdb/data:/var/lib/influxdb2
      - ./influxdb/config:/etc/influxdb2
    networks:
      service_vnet:
        
  grafana:
   image: grafana/grafana-oss:latest
   container_name: grafana
   user: "${UID}:${GID}"
   restart: always
   depends_on:
     - influxdb
   environment:
     - GF_INSTALL_PLUGINS=
   links:
     - influxdb
   expose:
     - "3000"
   volumes:
     - ./grafana:/var/lib/grafana
   networks:
     service_vnet:
    
  frigate:
    image: ghcr.io/blakeblackshear/frigate:stable
    container_name: frigate
    privileged: true
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
    shm_size: "256mb"
    expose:
      - "5000"
      - "8554" # RTSP feeds
      - "8555/tcp" # WebRTC over tcp
      - "8555/udp" # WebRTC over udp
      - "1935/tcp" # RTMP feed
    environment:
      - TZ=Europe/London
      - NVIDIA_DRIVER_CAPABILITIES=compute,video,utility
      - FLASK_ENV=development
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./frigate:/config
      - ${MEDIA_ROOT}/frigate:/media/frigate
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    networks:
     service_vnet:
  
  espresence:
   image: espresense/espresense-companion:latest
   container_name: "espresence_companion"
   user: "${UID}:${GID}"
   restart: always
   depends_on:
     - mqtt
   expose:
     - "8267"
   volumes:
     - ./espresence:/config/espresense
   networks:
     service_vnet:

  node-red:
    image: nodered/node-red:latest
    user: "${UID}:${GID}"
    environment:
      - TZ=Europe/London
    expose:
      - "1880"
    volumes:
      - ./nodered:/data
    networks:
     service_vnet:

  whisper:
    container_name: whisper
    user: "${UID}:${GID}"
    command: --model small --language en
    image: rhasspy/wyoming-whisper:latest
    volumes:
      - ./whisper:/data
    environment:
      - TZ=Europe/London
    restart: unless-stopped
    expose:
      - "10300"
    networks:
     service_vnet:

  piper:
    container_name: piper
    user: "${UID}:${GID}"
    image: rhasspy/wyoming-piper
    command: --voice en-gb-southern_english_female-low
    volumes:
      - ./piper:/data
    environment:
      - TZ=Europe/London
    restart: unless-stopped
    expose:
      - "10200"
    networks:
      service_vnet:

  geoipupdate:
    image: maxmindinc/geoipupdate
    container_name: geoipupdate
    environment:
      - GEOIPUPDATE_ACCOUNT_ID=${GEOIPUPDATE_ACCOUNT_ID}
      - GEOIPUPDATE_LICENSE_KEY=${GEOIPUPDATE_LICENSE_KEY}
      - GEOIPUPDATE_EDITION_IDS=GeoLite2-City
      - GEOIPUPDATE_FREQUENCY=24
    volumes:
      - ./geoip:/usr/share/GeoIP
    networks:
      service_vnet:

  npmgraf:
    image: smilebasti/npmgrafstats:latest
    restart: unless-stopped
    container_name: npmgraf
    environment:
      REDIRECTION_LOGS: 'FALSE'
      INTERNAL_LOGS: 'FALSE'
      MONITORING_LOGS: 'FALSE'
      INFLUX_HOST: 'http://influxdb:8086' # use host IP
      INFLUX_BUCKET: 'nginxproxy'
      INFLUX_ORG: 'Lonsdale'
      INFLUX_TOKEN: '${IF_NPM_TOKEN}'
    volumes:
      - ../proxy-manager/data_npm/logs:/logs
      - ./geoip:/geolite
    depends_on:
      - geoipupdate
    networks:
      service_vnet:

  music-assistant:
    container_name: musicassistant
    user: "${UID}:${GID}"
    image: ghcr.io/music-assistant/server:latest
    volumes:
      - ./musicassistant:/data
      - ${MUSIC_ROOT}:/media
    restart: unless-stopped
    privileged: true
    ports:
      - 8095:8095
    cap_add:
      - SYS_ADMIN
      - DAC_READ_SEARCH
    networks:
      service_vnet:
      iot_macvlan:
        ipv4_address: 192.168.160.101

  rhasspy3:
    container_name: rhasspy3
    image: registry.lonsdale.house/rhasspy3:latest
    volumes:
      - ./rhasspy/config:/root/rhasspy3/config
    restart: unless-stopped
    privileged: true
    ports:
      - 13331:13331
    environment:
      - TZ=Europe/London
      - PUID=${UID}
      - PGID=${GID}
    networks:
      service_vnet:
      iot_macvlan:
        ipv4_address: 192.168.160.60

networks:
  iot_macvlan:
    name: iot_macvlan
    external: true

  service_vnet:
    name: home_vnet
    external: true