# MQTT Connection, if empty will query and use hassio provided mqtt
mqtt:
  host: 192.168.160.151
  port: 1883
  ssl: false
  username:
  password:

# This gets added to the x,y,z to derive a gps location
gps:
  latitude: 53.72996027248322
  longitude: -0.4604924602243754
  elevation: 165

# How long before device considered stale
timeout: 30 # Seconds

# How long before device is considered away
away_timeout: 120 # Seconds

optimization:
  enabled: true
  interval_secs: 60
  limits:
    absorption_min: 2
    absorption_max: 5
    tx_ref_rssi_min: -70
    tx_ref_rssi_max: -50
    rx_adj_rssi_min: -20
    rx_adj_rssi_max: 20


weighting:
  algorithm: gaussian
  props:
    sigma: 0.10

floors:
  - id: level-38a7a668-1e4f-4f40-880e-d60bf5606c93
    name: ground_floor
    bounds: [[0, 0, 0], [16, 16, 0]]
    rooms:
      - name: living_room
        points:
        - [4.4, 4.2]
        - [4.4, 8.2]
        - [3.6, 8.2]
        - [3.6, 9.3]
        - [1.1, 9.3]
        - [1.1, 3.7]
        - [1.9, 3.7]
        - [2.3, 3.5]
        - [3.1, 3.5]
        - [3.5, 3.7]
        - [4.2, 3.7]
        - [4.4, 3.7]
      - name: closet
        points:
        - [4.4, 9.3]
        - [4.4, 8.3]
        - [3.7, 8.3]
        - [3.7, 9.3]
      - name: toilet
        points:
        - [6.5, 9.9]
        - [5.4, 9.9]
        - [5.4, 8.1]
        - [6.5, 8.1]
      - name: hallway
        points:
        - [4.4, 4.2]
        - [5.8, 4.2]
        - [5.8, 4.9]
        - [6.5, 4.9]
        - [6.5, 8]
        - [5.4, 8]
        - [5.4, 10]
        - [4.4, 10]
      - name: garage
        points:
        - [6.6, 10.3]
        - [9.2, 10.3]
        - [9.2, 4.6]
        - [6.6, 4.6]
      - name: utility
        points:
        - [7.3, 10.5]
        - [9.2, 10.5]
        - [9.2, 12.8]
        - [7.3, 12.8]
      - name: kitcehn
        points:
        - [6.5, 10]
        - [4.4, 10]
        - [4.4, 9.3]
        - [1.1, 9.3]
        - [1.1, 12.8]
        - [2.1, 12.8]
        - [2.1, 13.9]
        - [5.4, 13.9]
        - [5.4, 12.8]
        - [7.3, 12.8]
        - [7.3, 10.5]
        - [6.5, 10.5]
  - id: level-e490ce8b-992d-4c89-8f37-f4a880ddbea7
    name: upstairs
    bounds: [[0, 0, 2.1], [16, 16, 2.1]]
    rooms:
      - name: master_bedroom
        points:
        - [1.1, 7.4]
        - [5.4, 7.4]
        - [5.4, 6.3]
        - [6.5, 6.3]
        - [6.5, 4.9]
        - [4.3, 4.9]
        - [4.3, 3.7]
        - [1.1, 3.7]
      - name: guest_room
        points:
        - [6.6, 4.9]
        - [9.2, 4.9]
        - [9.2, 9.1]
        - [7.5, 9.1]
        - [7.5, 8.5]
        - [6.6, 8.5]
      - name: spare_room
        points:
        - [9.2, 12.8]
        - [9.2, 9.2]
        - [7.5, 9.2]
        - [7.5, 9.8]
        - [6.7, 9.8]
        - [6.7, 11.1]
        - [6.3, 11.1]
        - [6.3, 12.8]
      - name: landing
        points:
        - [7.5, 8.6]
        - [5.4, 8.6]
        - [5.4, 7.4]
        - [4.4, 7.4]
        - [4.4, 9.7]
        - [7.5, 9.7]
      - name: bathroom
        points:
        - [3.9, 12.8]
        - [6.2, 12.8]
        - [6.2, 11]
        - [6.6, 11]
        - [6.6, 9.8]
        - [4.6, 9.8]
        - [4.6, 11]
        - [3.9, 11]
      - name: office
        points:
        - [1.1, 12.8]
        - [1.1, 9.5]
        - [2.5, 9.5]
        - [2.5, 8.8]
        - [4.3, 8.8]
        - [4.3, 9.8]
        - [4.6, 9.8]
        - [4.6, 11]
        - [3.9, 11]
        - [3.9, 12.8]
      - name: en_suite
        points:
        - [1.1, 9.5]
        - [2.5, 9.5]
        - [2.5, 8.7]
        - [3.3, 8.7]
        - [3.3, 7.4]
        - [1.1, 7.4]
      - name: cupboard
        points:
        - [3.3, 8.7]
        - [4.3, 8.7]
        - [4.3, 7.4]
        - [3.3, 7.4]

# Locations of espresense nodes in meters
nodes:
  - name: landing
    point: [7.5, 9.1, 2.2]
    floors: ["level-e490ce8b-992d-4c89-8f37-f4a880ddbea7"]
  - name: office
    point: [2.8, 9.7, 2.2]
    floors: ["level-e490ce8b-992d-4c89-8f37-f4a880ddbea7"]
  - name: master_bedroom
    point: [4.1, 4.5, 2.2]
    floors: ["level-e490ce8b-992d-4c89-8f37-f4a880ddbea7"]
  - name: living_room
    point: [1.5, 5.8, 0]
    floors: ["level-38a7a668-1e4f-4f40-880e-d60bf5606c93"]
  - name: hallway
    point: [5.9, 4.8, 0]
    floors: ["level-38a7a668-1e4f-4f40-880e-d60bf5606c93"]
  - name: closet
    point: [4.3, 8.7, 0]
    floors: ["level-38a7a668-1e4f-4f40-880e-d60bf5606c93"]
  - name: kitchen
    point: [2.2, 13, 0]
    floors: ["level-38a7a668-1e4f-4f40-880e-d60bf5606c93"]
  - name: utility
    point: [7.2, 12, 0]
    floors: ["level-38a7a668-1e4f-4f40-880e-d60bf5606c93"]

# Devices to track
devices:
  - id: "irk:*" # Track all IRKs
  - id: "iBeacon:*"
  - id: "sonos:*"