- id: '1673386420495'
  name: Living Room Chill
  entities:
    light.far_end:
      min_color_temp_kelvin: 2000
      max_color_temp_kelvin: 6535
      min_mireds: 153
      max_mireds: 500
      effect_list:
      - None
      - candle
      - fire
      supported_color_modes:
      - color_temp
      - xy
      mode: normal
      dynamics: none
      friendly_name: Far End
      supported_features: 44
      state: 'off'
    light.lamp_2:
      min_color_temp_kelvin: 2000
      max_color_temp_kelvin: 6535
      min_mireds: 153
      max_mireds: 500
      effect_list:
      - None
      - candle
      - fire
      supported_color_modes:
      - color_temp
      - xy
      color_mode: color_temp
      brightness: 252
      color_temp_kelvin: 2409
      color_temp: 415
      hs_color:
      - 29.125
      - 75.922
      rgb_color:
      - 255
      - 155
      - 61
      xy_color:
      - 0.557
      - 0.389
      effect: None
      mode: normal
      dynamics: none
      friendly_name: Lamp
      supported_features: 44
      state: 'on'
    light.near_window:
      min_color_temp_kelvin: 2000
      max_color_temp_kelvin: 6535
      min_mireds: 153
      max_mireds: 500
      effect_list:
      - None
      - candle
      - fire
      supported_color_modes:
      - color_temp
      - xy
      mode: normal
      dynamics: none
      friendly_name: Near Window
      supported_features: 44
      state: 'off'
    light.signe_gradient_living_room:
      min_color_temp_kelvin: 2000
      max_color_temp_kelvin: 6535
      min_mireds: 153
      max_mireds: 500
      effect_list:
      - None
      - candle
      - fire
      - sunrise
      supported_color_modes:
      - color_temp
      - xy
      color_mode: color_temp
      brightness: 153
      color_temp_kelvin: 2832
      color_temp: 353
      hs_color:
      - 28.125
      - 61.661
      rgb_color:
      - 255
      - 171
      - 97
      xy_color:
      - 0.513
      - 0.386
      effect: None
      mode: normal
      dynamics: none
      friendly_name: Signe gradient living room
      supported_features: 44
      state: 'on'
    light.hallway_toilet:
      min_color_temp_kelvin: 2202
      max_color_temp_kelvin: 6535
      min_mireds: 153
      max_mireds: 454
      supported_color_modes:
      - color_temp
      mode: normal
      dynamics: none
      friendly_name: Outside Closet
      supported_features: 40
      color_mode: color_temp
      brightness: 84
      color_temp_kelvin: 3484
      color_temp: 287
      hs_color:
      - 27.189
      - 45.123
      rgb_color:
      - 255
      - 192
      - 139
      xy_color:
      - 0.456
      - 0.375
      state: 'on'
  icon: mdi:lamp-outline
  metadata:
    light.far_end:
      entity_only: true
    light.lamp_2:
      entity_only: true
    light.near_window:
      entity_only: true
    light.signe_gradient_living_room:
      entity_only: true
- id: '1673386578096'
  name: Living Room Daytime Chill
  entities:
    light.far_end:
      min_color_temp_kelvin: 2000
      max_color_temp_kelvin: 6535
      min_mireds: 153
      max_mireds: 500
      effect_list:
      - None
      - candle
      - fire
      supported_color_modes:
      - color_temp
      - xy
      mode: normal
      dynamics: none
      friendly_name: Far End
      supported_features: 44
      color_mode: rgb
      state: 'off'
    light.lamp_2:
      min_color_temp_kelvin: 2000
      max_color_temp_kelvin: 6535
      min_mireds: 153
      max_mireds: 500
      effect_list:
      - None
      - candle
      - fire
      supported_color_modes:
      - color_temp
      - xy
      color_mode: color_temp
      brightness: 255
      hs_color:
      - 27.303
      - 47.492
      rgb_color:
      - 255
      - 189
      - 133
      xy_color:
      - 0.464
      - 0.377
      effect: None
      mode: normal
      dynamics: none
      friendly_name: Lamp
      supported_features: 44
      color_temp_kelvin: 3378
      color_temp: 296
      state: 'on'
    light.near_window:
      min_color_temp_kelvin: 2000
      max_color_temp_kelvin: 6535
      min_mireds: 153
      max_mireds: 500
      effect_list:
      - None
      - candle
      - fire
      supported_color_modes:
      - color_temp
      - xy
      mode: normal
      dynamics: none
      friendly_name: Near Window
      supported_features: 44
      color_mode: rgb
      state: 'off'
    light.signe_gradient_living_room:
      min_color_temp_kelvin: 2000
      max_color_temp_kelvin: 6535
      min_mireds: 153
      max_mireds: 500
      effect_list:
      - None
      - candle
      - fire
      - sunrise
      supported_color_modes:
      - color_temp
      - xy
      color_mode: color_temp
      brightness: 184
      hs_color:
      - 27.85
      - 57.304
      rgb_color:
      - 255
      - 176
      - 108
      xy_color:
      - 0.498
      - 0.383
      effect: None
      mode: normal
      dynamics: none
      friendly_name: Signe gradient living room
      supported_features: 44
      color_temp_kelvin: 2985
      color_temp: 335
      state: 'on'
  icon: mdi:weather-sunny
  metadata:
    light.far_end:
      entity_only: true
    light.lamp_2:
      entity_only: true
    light.near_window:
      entity_only: true
    light.signe_gradient_living_room:
      entity_only: true
- id: '1673603753653'
  name: Work Time
  entities:
    light.adam_s_room:
      min_color_temp_kelvin: 2000
      max_color_temp_kelvin: 6535
      min_mireds: 153
      max_mireds: 500
      supported_color_modes:
      - color_temp
      - xy
      color_mode: color_temp
      brightness: 171
      color_temp_kelvin: 4444
      color_temp: 225
      hs_color:
      - 26.722
      - 27.373
      rgb_color:
      - 255
      - 216
      - 185
      xy_color:
      - 0.396
      - 0.357
      mode: normal
      dynamics: none
      friendly_name: Main
      supported_features: 40
      state: 'on'
    light.hue_play_left:
      min_color_temp_kelvin: 2000
      max_color_temp_kelvin: 6535
      min_mireds: 153
      max_mireds: 500
      supported_color_modes:
      - color_temp
      - xy
      color_mode: color_temp
      brightness: 255
      color_temp_kelvin: 4291
      color_temp: 233
      hs_color:
      - 26.727
      - 29.841
      rgb_color:
      - 255
      - 212
      - 178
      xy_color:
      - 0.405
      - 0.36
      mode: normal
      dynamics: none
      friendly_name: Hue play Left
      supported_features: 40
      state: 'on'
    light.hue_play_right:
      min_color_temp_kelvin: 2000
      max_color_temp_kelvin: 6535
      min_mireds: 153
      max_mireds: 500
      supported_color_modes:
      - color_temp
      - xy
      color_mode: color_temp
      brightness: 255
      color_temp_kelvin: 4291
      color_temp: 233
      hs_color:
      - 26.727
      - 29.841
      rgb_color:
      - 255
      - 212
      - 178
      xy_color:
      - 0.405
      - 0.36
      mode: normal
      dynamics: none
      friendly_name: Hue play Right
      supported_features: 40
      state: 'on'
  icon: mdi:chair-rolling
  metadata: {}
- id: '1673603790396'
  name: Play Time
  entities:
    light.adam_s_room:
      min_color_temp_kelvin: 2000
      max_color_temp_kelvin: 6535
      min_mireds: 153
      max_mireds: 500
      supported_color_modes:
      - color_temp
      - xy
      mode: normal
      dynamics: none
      friendly_name: Main
      supported_features: 40
      color_mode: color_temp
      brightness: 168
      color_temp_kelvin: 2645
      color_temp: 378
      hs_color:
      - 28.518
      - 67.51
      rgb_color:
      - 255
      - 164
      - 82
      xy_color:
      - 0.532
      - 0.388
      state: 'on'
    light.hue_play_left:
      min_color_temp_kelvin: 2000
      max_color_temp_kelvin: 6535
      min_mireds: 153
      max_mireds: 500
      supported_color_modes:
      - color_temp
      - xy
      color_mode: color_temp
      brightness: 219
      color_temp_kelvin: 3048
      color_temp: 328
      hs_color:
      - 27.748
      - 55.607
      rgb_color:
      - 255
      - 178
      - 113
      xy_color:
      - 0.492
      - 0.382
      mode: normal
      dynamics: none
      friendly_name: Hue play Left
      supported_features: 40
      state: 'on'
    light.hue_play_right:
      min_color_temp_kelvin: 2000
      max_color_temp_kelvin: 6535
      min_mireds: 153
      max_mireds: 500
      supported_color_modes:
      - color_temp
      - xy
      color_mode: color_temp
      brightness: 255
      color_temp_kelvin: 2967
      color_temp: 337
      hs_color:
      - 27.881
      - 57.799
      rgb_color:
      - 255
      - 176
      - 107
      xy_color:
      - 0.499
      - 0.384
      mode: normal
      dynamics: none
      friendly_name: Hue play Right
      supported_features: 40
      state: 'on'
  icon: mdi:nintendo-game-boy
  metadata: {}
- id: '1674841924278'
  name: Office Off
  entities:
    light.adam_s_room:
      min_color_temp_kelvin: 2000
      max_color_temp_kelvin: 6535
      min_mireds: 153
      max_mireds: 500
      supported_color_modes:
      - color_temp
      - xy
      mode: normal
      dynamics: none
      friendly_name: Main
      supported_features: 40
      state: 'off'
    light.hue_play_left:
      min_color_temp_kelvin: 2000
      max_color_temp_kelvin: 6535
      min_mireds: 153
      max_mireds: 500
      supported_color_modes:
      - color_temp
      - xy
      mode: normal
      dynamics: none
      friendly_name: Hue play Left
      supported_features: 40
      state: 'off'
    light.hue_play_right:
      min_color_temp_kelvin: 2000
      max_color_temp_kelvin: 6535
      min_mireds: 153
      max_mireds: 500
      supported_color_modes:
      - color_temp
      - xy
      mode: normal
      dynamics: none
      friendly_name: Hue play Right
      supported_features: 40
      state: 'off'
  icon: mdi:lightbulb-off
  metadata: {}
- id: '1674844091334'
  name: Living Room Off
  entities:
    light.far_end:
      min_color_temp_kelvin: 2000
      max_color_temp_kelvin: 6535
      min_mireds: 153
      max_mireds: 500
      effect_list:
      - None
      - candle
      - fire
      supported_color_modes:
      - color_temp
      - xy
      mode: normal
      dynamics: none
      friendly_name: Far End
      supported_features: 44
      state: 'off'
    light.near_window:
      min_color_temp_kelvin: 2000
      max_color_temp_kelvin: 6535
      min_mireds: 153
      max_mireds: 500
      effect_list:
      - None
      - candle
      - fire
      supported_color_modes:
      - color_temp
      - xy
      mode: normal
      dynamics: none
      friendly_name: Near Window
      supported_features: 44
      state: 'off'
    light.signe_gradient_living_room:
      min_color_temp_kelvin: 2000
      max_color_temp_kelvin: 6535
      min_mireds: 153
      max_mireds: 500
      effect_list:
      - None
      - candle
      - fire
      - sunrise
      supported_color_modes:
      - color_temp
      - xy
      mode: normal
      dynamics: none
      friendly_name: Signe gradient living room
      supported_features: 44
      state: 'off'
    light.lamp_2:
      min_color_temp_kelvin: 2000
      max_color_temp_kelvin: 6535
      min_mireds: 153
      max_mireds: 500
      effect_list:
      - None
      - candle
      - fire
      supported_color_modes:
      - color_temp
      - xy
      mode: normal
      dynamics: none
      friendly_name: Lamp
      supported_features: 44
      state: 'off'
  icon: mdi:lightbulb-off
  metadata: {}
