text_to_speech_on_sonos:
  alias: Text-to-Speech on Sonos
  use_blueprint:
    path: Talvish/sonos_say.yaml
  icon: mdi:account-voice
  mode: single
living_chill_script:
  alias: Living Chill Script
  sequence:
  - service: scene.turn_on
    target:
      entity_id: scene.hallway_path
    metadata: {}
  - service: scene.turn_on
    target:
      entity_id: scene.living_room_chill
    metadata: {}
  mode: single
