version: "3.4"

services:
  postgresql:
    image: postgres:9.6
    environment:
      POSTGRES_DB: etherpad
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

  etherpad:
    image: etherpad/etherpad:latest
    environment:
      DB_HOST: postgresql
      DB_NAME: etherpad
      DB_PASS: ${DB_PASSWORD}
      DB_PORT: 5432
      DB_TYPE: postgres
      DB_USER: ${DB_USER}
      LOGLEVEL: "debug"
      ROARR_LOG: "true"
      SKIN_NAME: "education"
      ETHERPAD_PLUGINS: "ep_align ep_comments_page ep_cursortrace ep_markdown ep_headings2 ep_font_size ep_author_hover"
    user: "${UID}:${GID}"
    expose:
      - "9001"
    volumes:
      - ./private/SESSIONKEY.txt:/app/SESSIONKEY.txt
      - ./private/APIKEY.txt:/app/APIKEY.txt
      - ./src/static/skins/education:/app/src/static/skins/education
      - ./src/plugins/ep_lightship:/app/node_modules/ep_lightship
      - ./settings.json:/app/settings.json
    depends_on:
      - postgresql
      - graylog

  mongo:
    image: mongo:3

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.8.5
    environment:
      http.host: "0.0.0.0"
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"

  graylog:
    image: graylog/graylog:3.2
    environment:
      GRAYLOG_PASSWORD_SECRET: ${GRAYLOG_SECRET}
      GRAYLOG_ROOT_PASSWORD_SHA2: ${GRAYLOG_PASSWORD}
      GRAYLOG_HTTP_EXTERNAL_URI: "http://127.0.0.1:9000/"
      GRAYLOG_CONTENT_PACKS_LOADER_ENABLED: "true"
      GRAYLOG_CONTENT_PACKS_AUTO_INSTALL: gelf-udp-input.json
    expose:
      - "9000"
    volumes:
      - ./docker/files/usr/share/graylog/data/contentpacks:/usr/share/graylog/data/contentpacks
    depends_on:
      - mongo
      - elasticsearch

  dockerize:
    image: jwilder/dockerize

  netshoot:
    image: nicolaka/netshoot
