version: '3'
services:
  broker:
    image: docker.io/library/redis:7
    user: "${UID}:${GID}"
    restart: unless-stopped
    volumes:
      - ./redisdata:/data
    environment:
      PUID: "${UID}"
      PGID: "${GID}"
    networks:
     service_vnet:

  paperless_db:
    image: docker.io/library/mariadb:10
    user: "${UID}:${GID}"
    restart: unless-stopped
    environment:
      PUID: "${UID}"
      PGID: "${GID}"
    volumes:
      - ./dbdata:/var/lib/mysql
    networks:
     service_vnet:

  paperless_ui:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    restart: unless-stopped
    depends_on:
      - paperless_db
      - broker
      - gotenberg
      - tika
    expose:
      - "8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - ./data:/usr/src/paperless/data
      - ./media:/usr/src/paperless/media
      - ./export:/usr/src/paperless/export
      - ./consume:/usr/src/paperless/consume
    networks:
     service_vnet:

  gotenberg:
    image: docker.io/gotenberg/gotenberg:7.8
    user: "${UID}:${GID}"
    restart: unless-stopped
    command:
      - "gotenberg"
      - "--chromium-disable-javascript=true"
      - "--chromium-allow-list=file:///tmp/.*"
    networks:
     service_vnet:

  tika:
    image: ghcr.io/paperless-ngx/tika:latest
    user: "${UID}:${GID}"
    restart: unless-stopped
    networks:
     service_vnet:

networks:
  service_vnet:
    name: paperless_vnet
    external: true