version: '3.8'
services:
  nginx-proxy-manager:
    container_name: nginx-proxy-manager
    image: 'jc21/nginx-proxy-manager:latest'
    ports:
      - '80:80'
      - '83:81'
      - '443:443'
    volumes:
      - ./data_npm:/data
      - ./letsencrypt:/etc/letsencrypt
    restart: always
    environment:
      X_FRAME_OPTIONS: "sameorigin"
      DB_SQLITE_FILE: "/data/database.sqlite"
      TZ: "Europe/London"
      PUID: "${UID}"
      PGID: "${GID}"
    networks:
      - home_vnet

  fail2ban:
    image: crazymax/fail2ban:latest
    container_name: fail2ban
    network_mode: "host"
    environment:
      PUID: "${UID}"
      PGID: "${GID}"
    cap_add:
      - NET_ADMIN
      - NET_RAW
    privileged: true
    volumes:
      - "./data_f2b:/data"
      - "./data_npm/logs/:/var/log/npm/:ro"
    restart: always
    env_file:
      - "./fail2ban.env"
    depends_on:
      - nginx-proxy-manager
  
  registry:
    restart: always
    container_name: registry
    image: registry:2
    expose:
      - 5000:5000
    volumes:
      - ./data_registry:/var/lib/registry
      - ./certs:/certs
      - ./auth:/auth
    environment:
      PUID: "${UID}"
      PGID: "${GID}"
    networks:
      - home_vnet

  registry-ui:
    image: joxit/docker-registry-ui:latest
    container_name: registryui
    expose:
      - "80"
    environment:
      - REGISTRY_TITLE=Lonsdale Registry
      - NGINX_PROXY_PASS_URL=http://registry:5000
      - NGINX_PROXY_HEADER_X_Forwarded_For=$$proxy_add_x_forwarded_for
      - SINGLE_REGISTRY=true
      - PUID=${UID}
      - PGID=${GID}
    volumes:
      - ./nginx.env:/etc/nginx/.env
    depends_on:
      - registry
    networks:
      - home_vnet

networks:
  home_vnet:
    name: home_vlan
    external: true
