version: '3'
services:
  snipeit:
    image: snipe/snipe-it
    container_name: snipeit
    restart: unless-stopped
    env_file: snipeit.env
    environment:
      - PUID=${UID}
      - PGID=${GID}
    expose: 
      - "80"
      - "443"
    depends_on:
      - snipeit_db
    volumes:
      - ./data:/var/lib/snipeit
    networks:
     service_vnet:
  
  snipeit_db:
    image: mysql:5.6
    container_name: snipeit_db
    user: "${UID}:${GID}"
    restart: unless-stopped
    env_file: snipeit.env
    volumes:
      - ./db:/var/lib/mysql
    networks:
     service_vnet:

networks:
  service_vnet:
    name: snipeit_vnet
    external: true