version: '3'
services:
  snipeit:
    image: snipe/snipe-it
    container_name: snipeit
    user: "${UID}:${GID}"
    restart: unless-stopped
    env_file: snipeit.env
    expose: 
      - "80"
    depends_on:
      - snipeit_db
    volumes:
      - ${HOME_ROOT}/snipeit/data:/var/lib/snipeit
    networks:
     home_vnet:
  
  snipeit_db:
    image: mysql:5.6
    container_name: snipeit_db
    user: "${UID}:${GID}"
    restart: unless-stopped
    env_file: snipeit.env
    volumes:
      - ${HOME_ROOT}/snipeit/db:/var/lib/mysql
    networks:
     home_vnet:

networks:
  home_vnet:
    name: home_vlan
    external: true