version: '3'
services:
  vikunja_db:
    image: mariadb:10
    user: "${UID}:${GID}"
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ${HOME_ROOT}/vikunja/db:/var/lib/mysql
    restart: unless-stopped
    networks:
     home_vnet:

  vikunja_api:
    image: vikunja/api
    user: "${UID}:${GID}"
    environment:
      VIKUNJA_DATABASE_HOST: vikunja_db
      VIKUNJA_DATABASE_TYPE: mysql
      VIKUNJA_SERVICE_FRONTENDURL: https://todo.lonsdale.house/
    expose:
      - "3456"
    volumes:
      - ${HOME_ROOT}/vikunja/api:/app/vikunja/files
    depends_on:
      - vikunja_db
    restart: unless-stopped
    networks:
     home_vnet:
  
  vikunja_frontend:
    image: vikunja/frontend
    user: "${UID}:${GID}"
    expose:
      - "80"
    environment:
      VIKUNJA_API_URL: https://todo.lonsdale.house/api/v1
    restart: unless-stopped
    networks:
     home_vnet:

networks:
  home_vnet:
    name: home_vlan
    external: true