mqtt:
  host: "mqtt"
  user: "{FRIGATE_MQTT_USER}"
  password: "{FRIGATE_MQTT_PASSWORD}"

detectors:
  coral:
    type: edgetpu
    device: usb

objects:
  track:
    - person
    - bicycle
    - car
    - motorcycle
    - bird
    - cat
    - dog
    - horse
    - sheep
    - cow
    - elephant
    - bear
    - zebra
    - giraffe
    - sports ball

go2rtc:
  rtsp:
    username: "{FRIGATE_RTSP_USER}"
    password: "{FRIGATE_RTSP_PASSWORD}"
  streams:
    kitchen_hd:
      - "ffmpeg:rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.160.22:554/stream1#video=copy#audio=copy#audio=opus"
    kitchen_sd:
      - "ffmpeg:rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.160.22:554/stream2#video=copy#audio=copy#audio=opus"
    outside_hd:
      - "ffmpeg:rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.160.23:554/stream1#video=copy#audio=copy#audio=opus"
    outside_sd:
      - "ffmpeg:rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.160.23:554/stream2#video=copy#audio=copy#audio=opus"
    office_hd:
      - "ffmpeg:rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.160.170:554/stream1#video=copy#audio=copy#audio=opus"
    office_sd:
      - "ffmpeg:rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.160.170:554/stream2#video=copy#audio=copy#audio=opus"
  webrtc:
    candidates:
      - frigate.lonsdale.house:8555
      - 172.22.0.201:8555

record:
  enabled: True
  events:
    retain:
      default: 6
      mode: active_objects
      objects:
        cat: 2

detect:
  stationary:
    interval: 0
    threshold: 50

cameras:
  kitchen:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/kitchen_sd
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/kitchen_hd
          input_args: preset-rtsp-restream
          roles:
            - detect
    live:
      stream_name: kitchen_sd
    snapshots:
      enabled: True
      bounding_box: True
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      height: 500

  outside:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/outside_sd
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/outside_hd
          input_args: preset-rtsp-restream
          roles:
            - detect
    live:
      stream_name: outside_sd
    snapshots:
      enabled: True
      bounding_box: True
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      height: 500

  office:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/office_sd
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/office_hd
          input_args: preset-rtsp-restream
          roles:
            - detect
    live:
      stream_name: office_sd
    snapshots:
      enabled: True
      bounding_box: True
    mqtt:
      timestamp: False
      bounding_box: False
      crop: True
      height: 500

ui:
  live_mode: jsmpeg
  timezone: Europe/London
  use_experimental: True
  time_format: browser
  date_style: short
  time_style: medium