on:
  push:
      branches:
      - 'main'
  workflow_dispatch:
  repository_dispatch:
  
jobs:
  deploy_request:
    runs-on: ubuntu-latest
    steps:
    - name: Call Deployment Action
      run: |
        curl -X POST https://api.github.com/repos/adamlonsdale/home-assistant-deploy/dispatches \
        -H 'Accept: application/vnd.github.everest-preview+json' \
        -u ${{ secrets.ACCESS_TOKEN }} \
        -d '{"event_type":"deploy-docker-prod"}'
